INSERT INTO major (major_id, major_short_name, major_long_name) VALUES
(1, 'undc', 'Undeclared'),
(2, 'csc', 'Computer Science'),
(3, 'phil', 'Philosophy'),
(4, 'acct', 'Accounting'),
(5, 'bus', 'Business'),
(6, 'econ', 'Economics'),
(7, 'eng', 'English'),
(8, 'hist', 'History'),
(9, 'art', 'Art'),
(10, 'phys', 'Physics')
;

INSERT INTO course (major,`number`,title) VALUES 
(2, 648,'Software Development'),
(2, 642,'Human Computer Interaction'),
(2, 600,'Programing Paradigms and Languages'),
(2, 645,'Computer Networks'),
(2, 690,'Interactive Multimedia Development'),
(3, 101,'Introduction to Philosophy'),
(3, 210,'Great Thinkers: East and West'),
(3, 621,'Minds, Brains, and Computers'),
(4, 100, 'Introduction to Financial Accounting'),
(4, 301, 'Intermediate Financial Accounting I'),
(4, 780, 'Financial Accounting'),
(5, 350, 'Introduction to Entrepeneurship'),
(5, 450, 'Greening of Business'),
(5, 682, 'Seminar on Business and Society'),
(5, 690, 'Seminar in Business Policy and Strategic Management'),
(6, 101, 'Introduction to Microeconomic Analysis'),
(6, 301, 'Introduction to Macroeconomic Theory'),
(6, 312, 'Introduction to Econometrics'),
(7, 114, 'Writing the First Year: Finding Your Voice'),
(7, 300, 'Graphic Memoir and Biography'),
(7, 402, 'Introduction to Professional Writing and Rhetoric'),
(7, 418, 'Grammar for Writers'),
(7, 465, 'Post-Apocalyptic Science Fiction'),
(8, 450, 'History of California'),
(8, 479, 'The History of Baseball'),
(8, 690, 'Editing and Publishing the History Journal'),
(9, 231, 'Introduction to Drawing'),
(9, 434, 'Color Workshop'),
(9, 671, 'Internship in the Visual Arts'),
(10, 440, 'Computational Physics'),
(10, 704, 'Electrodynamics')
;
